---
title: "LineGraphWrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(janitor)
library(tidytext)
library(wordcloud)
library(textdata)
library(ggplot2)
```

```{r}
biden_linegraph_vector <- (list.files(path = "biden_speeches"))[1:167]
```

```{r}
all_biden_linegraph <- data.frame()
for(i in 1:167){
  Biden_i <- read_tsv(paste0("biden_speeches/", biden_linegraph_vector[i]), col_names = FALSE) %>%
    mutate(file = biden_linegraph_vector[i])
  all_biden_linegraph <- bind_rows(all_biden_linegraph, Biden_i)
}
```

```{r}
trump_linegraph_vector <- (list.files(path = "trump_speeches"))
```

```{r}
all_trump_linegraph <- data.frame()
for(j in 1:119){
  Trump_j <- read_tsv(paste0("trump_speeches/", trump_linegraph_vector[j]), col_names = FALSE) %>%
    mutate(file = trump_linegraph_vector[j])
  all_trump_linegraph <- bind_rows(all_trump_linegraph, Trump_j)
}
```

```{r}
biden_linegraph_words <- all_biden_linegraph %>%
  unnest_tokens(output = word, input = X1)
```

```{r}
biden_linegraph_words2 <- biden_linegraph_words %>%
  anti_join(stop_words, by = "word")
```

```{r}
trump_linegraph_words <- all_trump_linegraph %>%
  unnest_tokens(output = word, input = X1)
```

```{r}
trump_linegraph_words2 <- trump_linegraph_words %>%
  anti_join(stop_words, by = "word")
```

```{r}
biden_linegraph_words3 <- biden_linegraph_words2 %>%
  count(file, word, sort = TRUE)
```

```{r}
trump_linegraph_words3 <- trump_linegraph_words2 %>%
  count(file, word, sort = TRUE)
```

```{r}
biden_linegraph_words3$file <- gsub(".txt", "", biden_linegraph_words3$file)
```

```{r}
trump_linegraph_words3$file <- gsub(".txt", "", trump_linegraph_words3$file)
```

```{r}
biden_linegraph_words3 %>%
  filter(word == "america") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "blue", size = 0.5) + geom_point(color = "blue") + labs(title = "Biden's use of the word 'America' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```

```{r}
trump_linegraph_words3 %>%
  filter(word == "america") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "red", size = 0.5) + geom_point(color = "red") + labs(title = "Trump's use of the word 'America' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```

```{r}
biden_linegraph_words3 %>%
  filter(word == "president") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "blue", size = 0.5) + geom_point(color = "blue") + labs(title = "Biden's use of the word 'president' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```

```{r}
trump_linegraph_words3 %>%
  filter(word == "president") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "red", size = 0.5) + geom_point(color = "red") + labs(title = "Trump's use of the word 'president' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```

```{r}
biden_linegraph_words3 %>%
  filter(word == "virus") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "blue", size = 0.5) + geom_point(color = "blue") + labs(title = "Biden's use of the word 'virus' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```

```{r}
trump_linegraph_words3 %>%
  filter(word == "virus") %>%
  ggplot(aes(x = as.Date(file, "%m-%d-%y"), y = n)) + geom_line(color = "red", size = 0.5) + geom_point(color = "red") + labs(title = "Trump's use of the word 'virus' over time.", x = "Date", y = "Word Frequency per Day") + theme_minimal()
```










